### ISSUE TITLE
Dicom files

### ISSUE THREAD

**Issue by yimuu** [GriffinLiang/AISD#5]
'0091465', '0091468', '0091505', '0091519' in dicom is empty.dicom文件和png文件不是对应的吗

**Comment by GriffinLiang** [comment]
Four missing dicom files('0091465', '0091468', '0091505', '0091519') can be downloaded from [dicom-3.tar.gz](https://pan.baidu.com/s/1Rblm1fU6xrpYSQub45f-Ig) with the password "aisd". Thanks for pointing this out.
