### ISSUE TITLE
No Download from the US possible

### ISSUE THREAD

**Issue by SophieOstmeier** [GriffinLiang/AISD#9]
Hi Kongming,

That for making your dataset public!
I cannot download your dataset from the US. Baidu does not allow an oversea account and downloading without an account did not work. Would it be possible to download your dataset from somewhere else?

Thank you!

Best, 
Sophie

**Comment by GriffinLiang** [comment]
Is it possible to find a Chinese colleague to download the data for you?

**Comment by 8s1o3s7t7m** [comment]
Hi, thanks for your reply. 
Not at someone who is located in China at the moment. 
Would there be another way to download the data?

**Comment by GriffinLiang** [comment]
The Google Drive link of the AISD dataset has been added in README.
